GET http://localhost:3000/api/campgrounds HTTP/1.1

###

POST http://localhost:3000/api/campgrounds HTTP/1.1
content-type: application/json

{
  "title": "Hey",
  "price":  "hey"
}

###

GET http://localhost:3000/api/campground/ HTTP/1.1


